name: FibBot Workflow
on: [push]
jobs:
     fibbot:
          runs-on: ubuntu-latest
          steps:
           - name: Checkout Repository
             uses: actions/checkout@v2
           - name: Run FibBot
             uses: ./fibbot
             with:
               enable_fib: 'true'
               max_threshold: '1000'
